"""Trim CHANGES.md down to changes that altered how a boon/upgrade works, and add
the fully removed ones -- the two things worth reading before touching a mod that
edits this content.

Classification, per entry in the CHANGED list. "Removed" here means the whole
boon/upgrade is gone -- that's the fully-cut list, shown separately. A field
merely disappearing or appearing *inside* an entry that still exists doesn't
count on its own; only a field whose value actually changed identity does,
ignoring RarityLevels (the game grew a Common rarity tier across almost every
entry over time) and the ExtractValues tooltip-formatting flags in
TUNING_FIELD_NAMES:
  - falls back to a raw text diff in changes.py (nothing scalar captured the
    change, so it's a shape change: reordered args, a swapped function, a new
    branch) -> high-level
  - a field's value type changed, or a string/bool field changed -> high-level
    (a renamed projectile, retargeted function, flipped flag -- not a number
    tune, and not a field just being added or removed)
  - everything left -- a same-type value edit, or any bare addition/removal --
    is a tweak, dropped

This is a heuristic over the same field diff changes.py computes, not a read of
intent -- skim the dropped tweaks in CHANGES.md too if a specific number matters.
Headers use the in-game display name; the internal name (needed to find the
entry in code or `Debug.GrantTraits`) rides along in backticks.
"""
import os, io
from harvest import WEAPONS, GODS, CURRENT, collect, hammer_names
from changes import (load_summary, original_source, diff_entry, format_diff, OUT)
from names import display_of, cut_source_build

# ExtractValues display flags: how a tooltip number is rounded/signed/shown, not
# what the boon does. These come and go as the tooltip schema evolves, same as
# RarityLevels gaining a Common tier -- ignore both for the high-level call.
TUNING_FIELD_NAMES = {"DecimalPlaces", "HideSigns", "IncludeSigns", "AsInt",
                       "ExcludeLinked", "SourceIsMultiplier"}


def is_tuning_field(key):
    parts = key.split("/")
    return "RarityLevels" in parts or parts[-1] in TUNING_FIELD_NAMES


def is_high_level(diffs):
    if diffs is None:
        return True
    for key, kind, old, new in diffs:
        if kind != "changed" or is_tuning_field(key):
            continue
        if not (isinstance(old, float) and isinstance(new, float)):
            return True
    return False


def label(name, build):
    disp = display_of(build, name)
    return "%s (`%s`)" % (disp, name) if disp else "`%s`" % name


def write_removed(out, title, cut_names, refdir):
    if not cut_names:
        return
    out.write("**Removed:** ")
    parts = [label(name, cut_source_build(refdir, name)) for name in sorted(cut_names)]
    out.write(", ".join(parts) + "\n\n")


def write_section(out, title, s, refdir, current_src):
    if not s["cut"] and not s["changed"]:
        return
    out.write("### %s\n\n" % title)
    write_removed(out, title, s["cut"], refdir)
    shown = False
    for name in sorted(s["changed"]):
        if name not in current_src:
            continue
        build, orig_lines = original_source(refdir, name)
        cur_lines = current_src[name][1].splitlines()
        diffs, unified = diff_entry(name, orig_lines, cur_lines)
        if not is_high_level(diffs):
            continue
        shown = True
        out.write("**%s** (since %s)\n\n" % (label(name, CURRENT), build))
        kept = [d for d in diffs if d[1] == "changed" and not is_tuning_field(d[0])] if diffs else []
        if kept:
            for d in kept:
                out.write("- %s\n" % format_diff(*d))
        else:
            out.write("Reshaped rather than retuned; see `CHANGES.md` for the raw diff.\n")
        out.write("\n")
    if not shown and not s["cut"]:
        out.write("_Only numeric tuning or field-level add/remove here -- see `CHANGES.md`._\n\n")


def main():
    summary = load_summary()
    out_path = os.path.join(os.path.dirname(__file__), "HIGHLIGHTS.md")
    out = io.open(out_path, 'w', encoding='utf-8')
    out.write("# High-level changes and removals\n\n")
    out.write("Generated by `highlights.py` from `CHANGES.md`'s field diffs: whole boons/upgrades\n")
    out.write("that were cut, plus surviving entries whose behaviour was retargeted or reshaped.\n")
    out.write("Pure numeric retuning, and any field just appearing or disappearing inside an\n")
    out.write("entry that still exists, are left out -- a field-level add/remove isn't the same\n")
    out.write("as the boon itself being removed, and `CHANGES.md` has the full detail if a\n")
    out.write("specific field matters. This is a heuristic, not a judgment call about what\n")
    out.write("matters; skim `CHANGES.md` too before relying on an omission.\n\n")

    out.write("## Hammer upgrades\n\n")
    for w in WEAPONS:
        s = summary["hammers"][w]
        current_src = hammer_names(CURRENT, w)
        write_section(out, w, s, os.path.join(OUT, "hammers", w), current_src)

    out.write("## Boons\n\n")
    for g in GODS:
        s = summary["boons"][g]
        current_src = collect(CURRENT, ["TraitData_%s.lua" % g])
        write_section(out, g, s, os.path.join(OUT, "boons", g), current_src)

    out.close()
    print("wrote", out_path)


if __name__ == "__main__":
    main()
