"""Map every live, cut and changed boon / hammer upgrade to its in-game display name.

Reuses harvest.py's parsing and its already-written reference/summary.json for the
cut/changed name lists, then reads each entry's DisplayName out of the matching
build's TraitText.en.sjson: the current build for live and changed entries, the
build named in a cut entry's reference-file header for cut ones (some entries --
mostly non-boon plumbing traits -- carry no DisplayName at all and print blank).
"""
import os, re, io, json
from harvest import ARC, OUT, BUILDS, CURRENT, WEAPONS, GODS, collect, hammer_names

TEXT_ID = re.compile(r'Id\s*=\s*"([^"]+)"')
DISPLAY = re.compile(r'DisplayName\s*=\s*"((?:[^"\\]|\\.)*)"')
CUT_BUILD = re.compile(r'last present in (\S+)')


def text_map(build):
    path = os.path.join(ARC, build, "Content", "Game", "Text", "en", "TraitText.en.sjson")
    try:
        lines = io.open(path, encoding='utf-8-sig', errors='replace').read().splitlines()
    except OSError:
        return {}
    out, cur_id = {}, None
    for line in lines:
        m = TEXT_ID.search(line)
        if m:
            cur_id = m.group(1)
            continue
        d = DISPLAY.search(line)
        if d and cur_id is not None:
            out[cur_id] = d.group(1)
            cur_id = None
    return out


TEXT = {}  # build -> {id: display}


def display_of(build, name):
    if build not in TEXT:
        TEXT[build] = text_map(build)
    return TEXT[build].get(name, "")


def load_summary():
    with io.open(os.path.join(OUT, "summary.json"), encoding='utf-8') as f:
        return json.load(f)


def cut_source_build(refdir, name):
    path = os.path.join(refdir, name + ".lua")
    try:
        head = io.open(path, encoding='utf-8').read()
    except OSError:
        return CURRENT
    m = CUT_BUILD.search(head)
    return m.group(1) if m else CURRENT


def rows_for(refdir, live_names, cut_names, changed_names):
    rows = []
    for name in sorted(live_names):
        status = "changed" if name in changed_names else "live"
        rows.append((name, display_of(CURRENT, name), status))
    for name in sorted(cut_names):
        b = cut_source_build(refdir, name)
        rows.append((name, display_of(b, name), "cut (" + b + ")"))
    return rows


def main():
    summary = load_summary()
    out_path = os.path.join(os.path.dirname(__file__), "NAMES.md")
    out = io.open(out_path, 'w', encoding='utf-8')
    out.write("# Internal name to in-game name, every entry\n\n")
    out.write("Generated by `names.py` from the build archive. `now`/`changed` display names come\n")
    out.write("from the current build's `TraitText.en.sjson`; `cut` ones come from the last build\n")
    out.write("that had the entry, per its reference-file header. A blank display name means the\n")
    out.write("entry carries no player-facing text (plumbing, not a pickable boon/upgrade).\n\n")

    out.write("## Hammer upgrades\n\n")
    for w in WEAPONS:
        s = summary["hammers"][w]
        live = set(hammer_names(CURRENT, w))
        refdir = os.path.join(OUT, "hammers", w)
        rows = rows_for(refdir, live, s["cut"], set(s["changed"]))
        out.write("### %s\n\n" % w)
        out.write("| Internal name | In-game name | Status |\n| --- | --- | --- |\n")
        for name, disp, status in rows:
            out.write("| `%s` | %s | %s |\n" % (name, disp, status))
        out.write("\n")

    out.write("## Boons\n\n")
    for g in GODS:
        s = summary["boons"][g]
        files = ["TraitData_%s.lua" % g]
        live = set(collect(CURRENT, files))
        refdir = os.path.join(OUT, "boons", g)
        rows = rows_for(refdir, live, s["cut"], set(s["changed"]))
        out.write("### %s\n\n" % g)
        out.write("| Internal name | In-game name | Status |\n| --- | --- | --- |\n")
        for name, disp, status in rows:
            out.write("| `%s` | %s | %s |\n" % (name, disp, status))
        out.write("\n")

    out.close()
    print("wrote", out_path)


if __name__ == "__main__":
    main()
